{{- if .Values.externalSecret.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ include "backend.fullname" . }}

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: ClusterSecretStore

  target:
    name: {{ .Values.externalSecret.secretName }}

  data:
    {{- range $key, $value := .Values.externalSecret.data }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $value }}
    {{- end }}

{{- end }}